# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Footprint
                                 A QGIS plugin
 This plugin manages the footprint of aerial imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-12-04
        copyright            : (C) 2019 by GISCAN
        email                : contact@giscan.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'GISCAN'
__date__ = '2019-12-04'
__copyright__ = '(C) 2019 by GISCAN'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Footprint class from file Footprint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .footprint import Footprint
    return Footprint(iface)
